# link to ~/.config/helix/config.toml

theme = "rockesheller-dark"

[editor.soft-wrap]
enable = true

[editor.statusline]
left = ["mode", "spinner", "diagnostics", "version-control"]
center = ["file-name"]
right = ["position", "position-percentage", "file-type"]

# emacs keybinds
[keys.insert]
C-p = "move_line_up"
C-n = "move_line_down"
C-e = "goto_line_end_newline"
C-a = "goto_line_start"
C-f = "move_char_right"
C-b = "move_char_left"
