# .zshrc - sets configurations for interactive Zsh

autoload -U colors && colors
PROMPT="%(?.%F{green}%?.%F{red}%?) %F{cyan}%(4~|%-1~/.../%2~|%3~) $reset_color%(!.#.)) "

HISTSIZE=5000
SAVEHIST=5000
HISTFILE=$HOME/.zsh_history

autoload -U compinit
zstyle ":completion:*" menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

# environment variable aliases
alias e="$EDITOR"

# coreutil aliases
alias ls="ls -AXF --color=auto"
alias la="ls -AXF --color=auto"
alias ll="ls -lAXF --color=auto"
alias cp="cp -ri"
alias mv="mv -i"
alias rm="rm -ri"
alias mkdir="mkdir -pv"

# git aliases
alias g="git"
alias gs="git status -sb"
alias gss="git status"
alias ga="git add"
alias gaa="git add -A"
alias gc="git commit"
alias gcm="git commit -m"
alias gacm="git add -A && git commit -m"
alias gp="git push"

source $HOME/.config/zsh-autosuggestions/zsh-autosuggestions.zsh || \
    echo "zsh-autosuggestions not found, please run \`install_zsh_plugins\` and restart your terminal"
source $HOME/.config/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh || \
    echo "zsh-syntax-highlighting not found, please run \`install_zsh_plugins\` and restart your terminal"
source $HOME/.config/zsh-vi-mode/zsh-vi-mode.plugin.zsh || \
    echo "zsh-vi-mode not found, please run \`install_zsh_plugins\` and restart your terminal"

install_zsh_plugins() {
    if ! (command -v git) >/dev/null; then
        echo "git not found, please install it..."
        return
    fi

    mkdir -p $HOME/.config
    rm -rf $HOME/.config/zsh-autosuggestions
    rm -rf $HOME/.config/zsh-syntax-highlighting
    rm -rf $HOME/.config/zsh-vi-mode

    git clone https://github.com/zsh-users/zsh-autosuggestions.git \
        $HOME/.config/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
        $HOME/.config/zsh-syntax-highlighting
    git clone https://github.com/jeffreytse/zsh-vi-mode.git \
        $HOME/.config/zsh-vi-mode
}

function osc7-pwd() {
    emulate -L zsh # also sets localoptions for us
    setopt extendedglob
    local LC_ALL=C
    printf '\e]7;file://%s%s\e\' $HOST ${PWD//(#m)([^@-Za-z&-;_~])/%${(l:2::0:)$(([##16]#MATCH))}}
}

function chpwd-osc7-pwd() {
    (( ZSH_SUBSHELL )) || osc7-pwd
}
add-zsh-hook -Uz chpwd chpwd-osc7-pwd
